//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaroshevskiKursach.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfClothing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeOfClothing()
        {
            this.Clothes = new HashSet<Clothes>();
        }
    
        public int IdTypeOfClothing { get; set; }
        public int IdViewIdOfClothing { get; set; }
        public string NameIdTypeOfClothing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clothes> Clothes { get; set; }
        public virtual ViewOfClothing ViewOfClothing { get; set; }
    }
}
